Template.Web/Areas/Default/Controllers/DashboardController.cs
namespace Template.Web.Areas.Default.Controllers;

public sealed class DashboardController : BaseDefaultController
{
    [AllowAnonymous]
    [DefaultRoute]
    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }
}

Template.Web/Areas/Example/Controllers/DataController.cs
namespace Template.Web.Areas.Example.Controllers;

using Template.Web.Areas.Example.Models;

public sealed class DataController : BaseExampleController
{
    private const int PageSize = 15;

    private IMapper Mapper { get; }

    private DataService DataService { get; }

    public DataController(
        IMapper mapper,
        DataService dataService)
    {
        Mapper = mapper;
        DataService = dataService;
    }

    //--------------------------------------------------------------------------------
    // List
    //--------------------------------------------------------------------------------

    [HttpGet]
    public async ValueTask<IActionResult> List([FromQuery] DataListForm form)
    {
        if (ModelState.IsValid)
        {
            var parameter = Mapper.Map<DataSearchParameter>(form).SetSize(PageSize);
            ViewBag.Paged = await DataService.QueryAccountPagedAsync(parameter);
        }

        return View(form);
    }

    //--------------------------------------------------------------------------------
    // Import
    //--------------------------------------------------------------------------------

    // TODO

    //--------------------------------------------------------------------------------
    // Export
    //--------------------------------------------------------------------------------

    // TODO
}

Template.Web/Areas/Default/Views/Dashboard/Index.cshtml
@{
    ViewData.SetTitle("ダッシュボード");
}

<div class="row mb-3">
    <div class="col-sm-4">
        <div class="card shadow-sm">
            <div class="card-header p-1 text-center">
                <h4 class="m-0">一覧画面</h4>
            </div>
            <div class="card-body pt-1 pb-1">
                <ul class="list-unstyled mb-0">
                    <li><a asp-area="Example" asp-controller="Data" asp-action="List">一覧(検索/CSV)</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card shadow-sm">
            <div class="card-header p-1 text-center">
                <h4 class="m-0">Group2</h4>
            </div>
            <div class="card-body pt-1 pb-1">
                <ul class="list-unstyled mb-0">
                    <li>Example1</li>
                    <li>Example2</li>
                    <li>Example3</li>
                    <li>Example4</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card shadow-sm">
            <div class="card-header p-1 text-center">
                <h4 class="m-0">Group3</h4>
            </div>
            <div class="card-body pt-1 pb-1">
                <ul class="list-unstyled mb-0">
                    <li>Example1</li>
                    <li>Example2</li>
                    <li>Example3</li>
                    <li>Example4</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-4">
        <div class="card shadow-sm">
            <div class="card-header p-1 text-center">
                <h4 class="m-0">Group4</h4>
            </div>
            <div class="card-body pt-1 pb-1">
                <ul class="list-unstyled mb-0">
                    <li>Example1</li>
                    <li>Example2</li>
                    <li>Example3</li>
                    <li>Example4</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card shadow-sm">
            <div class="card-header p-1 text-center">
                <h4 class="m-0">管理</h4>
            </div>
            <div class="card-body pt-1 pb-1">
                <ul class="list-unstyled mb-0">
                    <li>Example1</li>
                    <li>Example2</li>
                    <li>Example3</li>
                    <li>Example4</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card shadow-sm">
            <div class="card-header p-1 text-center">
                <h4 class="m-0">その他</h4>
            </div>
            <div class="card-body pt-1 pb-1">
                <ul class="list-unstyled mb-0">
                    @* ReSharper disable Html.PathError *@
                    <li><a href="/swagger">Swagger</a></li>
                    <li><a href="/metrics">Prometheus</a></li>
                    <li><a href="/health">Health check</a></li>
                    @* ReSharper restore Html.PathError *@
                </ul>
            </div>
        </div>
    </div>
</div>